// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back._Data;

namespace back.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20210318003628_PopulaAlojamento")]
    partial class PopulaAlojamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("back._Models.Alojamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ocupado")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Alojamentos");
                });

            modelBuilder.Entity("back._Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DonoAnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoSaude")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoInternacao")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonoAnimalId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("back._Models.DonoAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonosAnimais");
                });

            modelBuilder.Entity("back._Models.Alojamento", b =>
                {
                    b.HasOne("back._Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("back._Models.Animal", b =>
                {
                    b.HasOne("back._Models.DonoAnimal", "Dono")
                        .WithMany()
                        .HasForeignKey("DonoAnimalId");

                    b.Navigation("Dono");
                });
#pragma warning restore 612, 618
        }
    }
}
